build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20
  amd64: ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Sports Live"
  org.opencontainers.image.description: "Reactive lighting for live football matches."
  org.opencontainers.image.source: "https://github.com/b12e/ha-sports-live"
  org.opencontainers.image.licenses: "MIT"
